# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb8ed5d11d2466f5172c51da3fb6af627dbf0a17d9146dfef05630ed755050295d6e1f9b619be29558767ecf6b255b416a778d6eefa9916b2999b1f386d25473

test:
  secret_key_base: 832729f36a013bc3bc68b9e92caf7ce197fb8b6b87d3f0f47ddb678b973542bb0e56e6fb966779aa9b20d52e55e7791127491fd025f15ae117518120a89d1f08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
